export default {
  import: {
    title: 'Import upstream keys',
    description: 'Create a Group or import only upstream keys into an existing Group.',
    progress: 'Import progress',
    steps: {
      '1': 'Connection',
      '2': 'Models',
      '3': 'Review',
    },
    presets: {
      openai: 'OpenAI',
      anthropic: 'Anthropic',
      gemini: 'Gemini',
      custom: 'Custom',
    },
    mode: {
      label: 'Import destination',
      new: 'New Group',
      existing: 'Existing Group',
    },
    operation: {
      reconciling:
        'The resource was committed and runtime recovery is still in progress. Check the result with the same operation.',
      indeterminate:
        'This operation could not be confirmed. Do not start another operation; use the action below to check the result.',
      waiting:
        'An earlier committed operation is still recovering. Retry this same operation after the wait.',
      expired:
        'The detailed result has expired. Verify only the resource identity manually and do not resubmit.',
      checkResult: 'Check result',
    },
    existing: {
      title: 'Import into an existing Group',
      description: 'Add upstream keys only. Models, protocols, and settings are not changed.',
      groupsLoading: 'Loading Groups…',
      groupsFailed: 'Unable to load Groups.',
      groupLabel: 'Destination Group',
      groupPlaceholder: 'Select a Group',
      reviewTitle: 'Review key import',
      reviewDescription: 'Confirm the destination and key count. Raw key values are not displayed.',
      submit: 'Import keys',
      importFailed: 'Unable to import keys into the selected Group.',
      successTitle: 'Keys imported',
      successSummary: '{added} added; {duplicated} already existed.',
    },
    connection: {
      title: 'Connect an upstream',
      description:
        'Choose a preset or enter a compatible upstream. Presets only fill URL and protocols.',
      preset: 'Channel preset',
      name: 'Group name (optional)',
      url: 'Upstream URL',
      protocols: 'Protocols',
      advanced: 'Advanced header rules',
    },
    keys: {
      label: 'Upstream keys',
      placeholder: 'One key per line',
      count: '{count} non-empty keys',
      empty: '{count} empty lines',
      duplicates: '{count} duplicate lines',
      accessKeyWarning: '{count} lines look like GPT-Load AccessKeys; verify before continuing.',
      tooMany: 'At most 1,000 non-empty keys can be submitted.',
    },
    headerRules: {
      title: 'Header rules',
      description: 'Set or remove upstream request headers.',
      storageNotice:
        'Password masking only reduces shoulder-surfing exposure; it is not encryption at rest. Ordinary HeaderRules literals are stored in plaintext in SQLite and backups. Provider credential headers must use the {template} template.',
      add: 'Add rule',
      action: 'Action',
      set: 'Set',
      remove: 'Remove',
      name: 'Header name',
      value: 'Header value',
      removeHint: 'This header will be removed.',
      delete: 'Delete rule',
      duplicate: 'duplicate header names are not allowed (case-insensitive).',
    },
    models: {
      title: 'Models and aliases',
      description: 'Select discovered models and add local aliases.',
      stepDescription:
        'Discovery is read-only. Review the candidates or continue with manual models.',
      alias: 'Local alias (optional)',
      aliasFor: 'Alias for {id}',
      manualId: 'Manual model ID',
      add: 'Add model',
      manualPath: 'Continue with manual model IDs',
    },
    discover: 'Discover models',
    discoveryFailed:
      'Discovery failed. Your draft is intact; you can retry or enter models manually.',
    back: 'Back',
    review: 'Review',
    reviewTitle: 'Review and create',
    reviewDescription:
      'Confirm the connection and models. Raw key values are never displayed in this review.',
    automaticName: 'Generated by the server',
    create: 'Create Group',
    createFailed: 'Unable to create the Group.',
    appendFailed: 'Unable to import keys into the selected Group.',
    conflict: {
      title: 'This upstream URL already exists',
      description: 'Choose how to continue.',
      append: 'Import keys here',
      separate: 'Create a separate Group',
      edit: 'Return to edit',
    },
    unsavedConfirm: 'Discard unsaved import changes?',
  },
} as const
